package com.rm.promotion.model

object DateFormatConstant {
    const val UTC = "UTC"

    const val E = "E"
    const val EEEE = "EEEE"
    const val MMMM = "MMMM"
    const val yyyy = "yyyy"
    const val hhmmss = "hhmmss"

    const val dd = "dd"
    const val d_MMM = "d MMM"
    const val dd_MM = "dd/MM"
    const val dd_MMM = "dd MMM"

    const val yyMMddHHmmss = "yyMMddHHmmss"
    const val yyyyMMdd = "yyyyMMdd"
    const val yyyyMMddHHmmss = "yyyyMMddHHmmss"
    const val yyyyMMdd_HHmmss = "yyyyMMdd_HHmmss"
    const val yyyyMMdd_hhmmssSSS = "yyyyMMdd_hhmmssSSS"
    const val yyyyMMdd_T_hhmmss = "yyyyMMdd'T'hhmmss"
    const val yyyyMMDD_T_HHMMSS = "yyyyMMDD'T'HHMMSS"

    const val H_mm = "H:mm"
    const val HH_mm = "HH:mm"
    const val HH_mm_ss = "HH:mm:ss"
    const val h_mm_aa = "h:mm aa"
    const val h_mm_ss_aa = "h:mm:ss aa"
    const val hh_mm_aa = "hh:mm aa"

    const val ddMMyyyy = "ddMMyyyy"
    const val d_MMM_yy = "d MMM yy"
    const val dd_MMM_yy_HH_mm = "dd MMM yy, HH:mm"
    const val d_MMM_yyyy = "d MMM yyyy"
    const val d_MMMM_yyyy = "d MMMM yyyy"
    const val dd_MM_yyyy_DASH = "dd-MM-yyyy"
    const val d_M_yy_SLASH = "d/M/yy"
    const val dd_MM_yyyy_SLASH = "dd/MM/yyyy"
    const val dd_MMM_yyy = "dd-MMM-yyy"
    const val dd_MMM_yyyy = "dd MMM yyyy"
    const val dd_MMMM_yyyy = "dd MMMM yyyy"
    const val MM_dd_yyyy = "MM-dd-yyyy"
    const val MMM_dd_yyyy = "MMM dd, yyyy"
    const val MMMM_dd_yyyy = "MMMM dd, yyyy"
    const val yyyy_MM_dd_DASH = "yyyy-MM-dd"
    const val yyyy_MM_dd_SLASH = "yyyy/MM/dd"

    const val E_d_MMM_HH_mm = "E d MMM, HH:mm"
    const val E_d_MMM_yyyy = "E d MMM yyyy"
    const val E_MMM_dd_HH_mm_ss_yyyy = "E MMM dd HH:mm:ss yyyy"
    const val EEE_d_MMM = "EEE d MMM"
    const val EEE_d_MMM_yyyy = "EEE d MMM yyyy"
    const val EEEE_d_MMM_yy = "EEEE d MMM yy"
    const val EEE_d_MMM_HH_mm = "EEE d MMM, HH:mm"
    const val E_d_MMM_yy = "E, d-MMM-yy"
    const val Ed_MMM = "E, d-MMM"
    const val EEEE_d_MMM = "EEEE d MMM"

    const val dd_M_yy = "dd/M/yy"
    const val dd_M_yyyy = "dd/M/yyyy"
    const val yyyy_M_dd = "yyyy-M-dd"
    const val dd_MM_yy_HH_mm = "dd/MM/yy HH:mm"
    const val dd_MM_yyyy_HH_mm = "dd/MM/yyyy HH:mm"
    const val dd_MM_yyyy_HH_mm_ss = "dd/MM/yyyy HH:mm:ss"
    const val dd_MMM_yyyy_HH_mm = "dd MMM yyyy HH:mm"
    const val yyyy_MM_dd_HH_mm = "yyyy-MM-dd HH:mm"
    const val yyyy_MM_dd_HH_mm_ss = "yyyy-MM-dd HH:mm:ss"
    const val yyyy_MM_dd_T_HH_mm_ss = "yyyy-MM-dd'T'HH:mm:ss"
    const val yyyyMMdd_T_HHmmss = "yyyyMMdd'T'HHmmss"

    const val yyyy_MM_dd_T_HH_mm_ss_Z = "yyyy-MM-dd'T'HH:mm:ss'Z'"
    const val yyyy_MM_dd_T_HH_mm_ss_SSS_Z = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
    const val yyyy_MM_dd_HH_mm_ss_SSS = "yyyy-MM-dd HH:mm:ss.SSS"

    const val yyyy_MM_dd_T_HH_mm_ss_SS_XXX = "yyyy-MM-dd'T'HH:mm:ss.SSXXX"
    const val yyyy_MM_dd_T_HH_mm_ss_SS_ZZZZZ = "yyyy-MM-dd'T'HH:mm:ss.SSZZZZZ"
}
